### ISSUE TITLE
无法使用组合键，比如：Ctrl+A 等等

### ISSUE THREAD

**Issue by jftrack** [xlydsg/RaspberryPiRemoteControl#2]
无法使用任何组合键，好像程序设定为只能单个按键

**Comment by xlydsg** [comment]
啊我应该没写相关映射，可以参考CH9329芯片串口通信协议补上去

**Comment by jftrack** [comment]
> 啊我应该没写相关映射，可以参考CH9329芯片串口通信协议补上去

水平有限，没折腾成功。。。能否麻烦项目主有时间抽空改下，

不过已经过去两年了，估计你自己都没在用了。。。感谢发布，很是实用，哈哈哈

**Comment by xlydsg** [comment]
> > 啊我应该没写相关映射，可以参考CH9329芯片串口通信协议补上去
> 
> 水平有限，没折腾成功。。。能否麻烦项目主有时间抽空改下，
> 
> 不过已经过去两年了，估计你自己都没在用了。。。感谢发布，很是实用，哈哈哈

确实，我连树莓派都卖掉了哈哈哈哈哈
